// ─── TOOL REGISTRY ───────────────────────────────────────────────────────────
// Central registry of all tools on the platform. Each tool has a slug, display
// name, description, category, icon name (from lucide-react), and metadata.

export type ToolDef = {
  slug: string;
  name: string;
  desc: string;
  category: string;
  categorySlug: string;
  icon: string;
  badge: string;
  color: string;
  darkColor: string;
  isClientSide: boolean;
  featured?: boolean;
  trending?: boolean;
  isLatest?: boolean;
  seoTitle?: string;
  seoDescription?: string;
};

export type CategoryDef = {
  slug: string;
  name: string;
  icon: string;
  color: string;
  darkColor: string;
  bgClass: string;
  desc: string;
};

export const CATEGORIES: CategoryDef[] = [
  {
    slug: "developer",
    name: "Developer",
    icon: "Braces",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    bgClass: "bg-[#EFF6FF] dark:bg-[#172554]/60",
    desc: "Essential utilities for developers — formatters, encoders, generators and more.",
  },
  {
    slug: "text",
    name: "Text",
    icon: "AlignLeft",
    color: "#D97706",
    darkColor: "#D97706",
    bgClass: "bg-[#FFFBEB] dark:bg-[#451A03]/60",
    desc: "Text manipulation tools — counters, converters, formatters for everyday writing.",
  },
  {
    slug: "pdf",
    name: "PDF",
    icon: "FileText",
    color: "#EF4444",
    darkColor: "#EF4444",
    bgClass: "bg-[#FEF2F2] dark:bg-[#450A0A]/60",
    desc: "Work with PDFs — merge, split, compress and convert documents.",
  },
  {
    slug: "image",
    name: "Image",
    icon: "Image",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    bgClass: "bg-[#F5F3FF] dark:bg-[#2E1065]/60",
    desc: "Image processing tools — compress, resize, convert and optimize visuals.",
  },
  {
    slug: "finance",
    name: "Finance",
    icon: "Calculator",
    color: "#22C55E",
    darkColor: "#22C55E",
    bgClass: "bg-[#F0FDF4] dark:bg-[#052E16]/60",
    desc: "Financial calculators and converters tailored for Nepali users.",
  },
  {
    slug: "nepal",
    name: "Nepal Tools",
    icon: "MapPin",
    color: "#DC2626",
    darkColor: "#F87171",
    bgClass: "bg-[#FFF1F2] dark:bg-[#450A0A]/60",
    desc: "Tools built specifically for Nepal — land conversion, date converters and more.",
  },
  {
    slug: "everyday",
    name: "Everyday",
    icon: "Sparkles",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    bgClass: "bg-[#F0FDFA] dark:bg-[#042F2E]/60",
    desc: "Everyday calculators and unit converters for students and professionals.",
  },
];


export const TOOLS: ToolDef[] = [
  // ── Developer ──
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    desc: "Format, minify, and validate JSON in one click",
    category: "Developer",
    categorySlug: "developer",
    icon: "Braces",
    badge: "Popular",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    featured: true,
    seoTitle: "JSON Formatter & Validator – Prettify & Validate JSON Online | SajiloTools",
    seoDescription: "Format, validate, and beautify JSON code instantly in your browser. Clean indenting, live syntax error detection, and 100% private client-side processing.",
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder / Decoder",
    desc: "Encode or decode Base64 strings instantly",
    category: "Developer",
    categorySlug: "developer",
    icon: "Code2",
    badge: "Fast",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
    seoTitle: "Base64 Encoder & Decoder – Free Online String Converter | SajiloTools",
    seoDescription: "Encode plain text to Base64 or decode Base64 strings back to text instantly. Safe, fast, and 100% free with browser-based privacy.",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    desc: "Percent-encode or decode URL components",
    category: "Developer",
    categorySlug: "developer",
    icon: "Link2",
    badge: "Free",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    desc: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text",
    category: "Developer",
    categorySlug: "developer",
    icon: "Hash",
    badge: "Fast",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
    seoTitle: "Hash Generator – MD5, SHA-1, SHA-256 & SHA-512 Online | SajiloTools",
    seoDescription: "Generate MD5, SHA-1, SHA-256, and SHA-512 cryptographic hashes from any text. Fast, free, client-side generation with zero server storage.",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    desc: "Test regular expressions with live highlighting",
    category: "Developer",
    categorySlug: "developer",
    icon: "Search",
    badge: "Popular",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    seoTitle: "Regex Tester & Debugger – Real-Time Regular Expression Checker | SajiloTools",
    seoDescription: "Test and debug JavaScript regular expressions in real time with live match highlighting, capture group breakdown, and pattern syntax validation.",
  },
  {
    slug: "color-picker",
    name: "Color Picker & Converter",
    desc: "Pick and convert colors between HEX, RGB, HSL",
    category: "Developer",
    categorySlug: "developer",
    icon: "Palette",
    badge: "Popular",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    desc: "Generate secure random passwords with customizable rules",
    category: "Developer",
    categorySlug: "developer",
    icon: "ShieldCheck",
    badge: "Free",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
    seoTitle: "Strong Password Generator \u2013 Free & Secure | SajiloTools",
    seoDescription: "Generate strong, random, secure passwords instantly. Customize length and character types. Free, private, runs in your browser.",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    desc: "Generate placeholder text for designs and mockups",
    category: "Developer",
    categorySlug: "developer",
    icon: "FileText",
    badge: "Free",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    desc: "Create QR codes for any URL or text instantly",
    category: "Developer",
    categorySlug: "developer",
    icon: "QrCode",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "timezone-converter",
    name: "Time Zone Converter",
    desc: "Convert times between any time zones with live multi-zone comparison and Nepal (UTC+5:45) support",
    category: "Developer",
    categorySlug: "developer",
    icon: "Clock",
    badge: "Popular",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    desc: "Write Markdown and preview the rendered HTML in real time",
    category: "Developer",
    categorySlug: "developer",
    icon: "FileText",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "link-shortener",
    name: "Link Shortener",
    desc: "Shorten long URLs with clean custom aliases",
    category: "Developer",
    categorySlug: "developer",
    icon: "Link2",
    badge: "Popular",
    color: "#D97706",
    darkColor: "#D97706",
    isClientSide: false,
    featured: true,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    desc: "Generate v4 UUIDs individually or in bulk, with copy and export",
    category: "Developer",
    categorySlug: "developer",
    icon: "Fingerprint",
    badge: "Fast",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    seoTitle: "UUID Generator \u2013 Free Online, Bulk & v4 | SajiloTools",
    seoDescription: "Generate v4 UUIDs instantly, in bulk if needed. Free, fast, and private \u2014 works entirely in your browser.",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    desc: "Decode JWT tokens to inspect header and payload, with optional HMAC signature verification",
    category: "Developer",
    categorySlug: "developer",
    icon: "KeySquare",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    seoTitle: "JWT Decoder & Parser – Decode JSON Web Tokens Online | SajiloTools",
    seoDescription: "Decode JSON Web Tokens (JWT) instantly to inspect header, payload, and signature claims. 100% client-side decoding keeps token secrets private.",
  },
  {
    slug: "unix-timestamp-converter",
    name: "Unix Timestamp Converter",
    desc: "Convert Unix epoch timestamps to human-readable dates and back, in any timezone",
    category: "Developer",
    categorySlug: "developer",
    icon: "Clock4",
    badge: "Popular",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
  },
  {
    slug: "css-js-minifier",
    name: "CSS & JS Minifier",
    desc: "Minify CSS or JavaScript by removing whitespace, comments, and shortening code",
    category: "Developer",
    categorySlug: "developer",
    icon: "FileArchive",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    desc: "Generate cryptographic HMAC signatures using SHA-256, SHA-512, MD5, or SHA-1 with custom secret keys",
    category: "Developer",
    categorySlug: "developer",
    icon: "ShieldCheck",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "random-token-generator",
    name: "Random Token Generator",
    desc: "Generate cryptographically secure API keys, secret tokens, hex strings, and bulk random keys",
    category: "Developer",
    categorySlug: "developer",
    icon: "KeySquare",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "file-checksum-verifier",
    name: "File Checksum Verifier",
    desc: "Verify file integrity locally by calculating SHA-256, SHA-512, SHA-1, and MD5 hashes without uploading files",
    category: "Developer",
    categorySlug: "developer",
    icon: "FileCheck",
    badge: "New",
    color: "#1F2544",
    darkColor: "#9AA3D6",
    isClientSide: true,
    featured: true,
  },

  // ── Text ──
  {
    slug: "word-counter",
    name: "Word Counter",
    desc: "Count words, characters, sentences, and paragraphs",
    category: "Text",
    categorySlug: "text",
    icon: "AlignLeft",
    badge: "Popular",
    color: "#D97706",
    darkColor: "#D97706",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    desc: "Transform text to UPPER, lower, Title, camelCase and more",
    category: "Text",
    categorySlug: "text",
    icon: "AlignLeft",
    badge: "Free",
    color: "#D97706",
    darkColor: "#D97706",
    isClientSide: true,
  },
  {
    slug: "text-diff",
    name: "Text Diff Checker",
    desc: "Compare two texts and highlight every difference",
    category: "Text",
    categorySlug: "text",
    icon: "AlignLeft",
    badge: "New",
    color: "#D97706",
    darkColor: "#D97706",
    isClientSide: true,
  },
  {
    slug: "string-utilities",
    name: "String Utilities",
    desc: "Reverse, trim, repeat, slugify and manipulate strings",
    category: "Text",
    categorySlug: "text",
    icon: "AlignLeft",
    badge: "Free",
    color: "#D97706",
    darkColor: "#D97706",
    isClientSide: true,
  },

  // ── PDF ──
  {
    slug: "pdf-merger",
    name: "PDF Merger",
    desc: "Combine multiple PDFs into one seamless file",
    category: "PDF",
    categorySlug: "pdf",
    icon: "FileText",
    badge: "Popular",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "pdf-splitter",
    name: "PDF Splitter",
    desc: "Extract or split pages from PDF files",
    category: "PDF",
    categorySlug: "pdf",
    icon: "FileText",
    badge: "Fast",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    desc: "Convert PDF text content into an editable Microsoft Word (.docx) document",
    category: "PDF",
    categorySlug: "pdf",
    icon: "FileText",
    badge: "New",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
    trending: true,
    isLatest: true,
  },
  {
    slug: "pdf-organizer",
    name: "PDF Organizer",
    desc: "Rotate, delete, and reorder PDF pages with drag-and-drop thumbnails",
    category: "PDF",
    categorySlug: "pdf",
    icon: "LayoutGrid",
    badge: "Popular",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
  },
  {
    slug: "pdf-watermark",
    name: "PDF Watermark",
    desc: "Add a text or image watermark across every page of your PDF",
    category: "PDF",
    categorySlug: "pdf",
    icon: "Stamp",
    badge: "New",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
  },
  {
    slug: "jpg-pdf-converter",
    name: "JPG ↔ PDF Converter",
    desc: "Convert JPG images into a PDF, or extract PDF pages as JPG images",
    category: "PDF",
    categorySlug: "pdf",
    icon: "FileImage",
    badge: "Popular",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
  },
  {
    slug: "pdf-compressor",
    name: "PDF Compressor",
    desc: "Shrink PDF file size by recompressing embedded images",
    category: "PDF",
    categorySlug: "pdf",
    icon: "Minimize2",
    badge: "Fast",
    color: "#EF4444",
    darkColor: "#EF4444",
    isClientSide: true,
  },

  // ── Image ──
  {
    slug: "image-compressor",
    name: "Image Compressor",
    desc: "Reduce image size without any visible quality loss",
    category: "Image",
    categorySlug: "image",
    icon: "Image",
    badge: "Popular",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    desc: "Resize images to exact dimensions or scale percentage",
    category: "Image",
    categorySlug: "image",
    icon: "Maximize2",
    badge: "Popular",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    desc: "Crop images visually with freeform or aspect ratio presets (1:1, 16:9, 4:3, 9:16)",
    category: "Image",
    categorySlug: "image",
    icon: "Crop",
    badge: "New",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    desc: "Convert images between PNG, JPEG, WebP and BMP formats",
    category: "Image",
    categorySlug: "image",
    icon: "RefreshCw",
    badge: "New",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
    trending: true,
    isLatest: true,
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    desc: "Convert images into Base64 strings, HTML tags, and CSS background URIs",
    category: "Image",
    categorySlug: "image",
    icon: "Code2",
    badge: "Free",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },
  {
    slug: "background-remover",
    name: "AI Background Remover",
    desc: "Remove image backgrounds with on-device AI — private, free, and no upload required",
    category: "Image",
    categorySlug: "image",
    icon: "Wand2",
    badge: "New",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
    trending: true,
    isLatest: true,
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    desc: "Generate a full favicon set (ICO, PNG sizes, Apple touch icon) from any image",
    category: "Image",
    categorySlug: "image",
    icon: "Squircle",
    badge: "Popular",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },
  {
    slug: "image-watermark",
    name: "Image Watermark",
    desc: "Add a text or logo watermark to your photos, single or in bulk",
    category: "Image",
    categorySlug: "image",
    icon: "Stamp",
    badge: "New",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },
  {
    slug: "image-rotate-flip",
    name: "Image Rotate & Flip",
    desc: "Rotate images 90/180/270° or flip horizontally and vertically",
    category: "Image",
    categorySlug: "image",
    icon: "FlipHorizontal",
    badge: "Fast",
    color: "#7C3AED",
    darkColor: "#A78BFA",
    isClientSide: true,
  },

  // ── Finance ──
  {
    slug: "nrs-converter",
    name: "NRs Currency Converter",
    desc: "Convert Nepali Rupees to any world currency with live NRB exchange rates",
    category: "Finance",
    categorySlug: "finance",
    icon: "Calculator",
    badge: "Live NRB",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: false,
    featured: true,
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    desc: "Calculate monthly EMI, total interest and amortization for NPR/INR loans",
    category: "Finance",
    categorySlug: "finance",
    icon: "Calculator",
    badge: "Popular",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "tax-calculator",
    name: "Income Tax & Salary TDS Calculator",
    desc: "Calculate Nepal income tax / Salary TDS with latest slabs for salaried individuals",
    category: "Finance",
    categorySlug: "finance",
    icon: "Calculator",
    badge: "Nepal",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "interest-calculator",
    name: "Interest Calculator (Simple & Compound)",
    desc: "Calculate simple and compound interest returns with flexible compounding frequency",
    category: "Finance",
    categorySlug: "finance",
    icon: "Percent",
    badge: "Popular",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
  },
  {
    slug: "pf-calculator",
    name: "Provident Fund (EPF / CIT / SSF) Calculator",
    desc: "Calculate employee and employer retirement fund growth and tax-free corpus projection",
    category: "Finance",
    categorySlug: "finance",
    icon: "Landmark",
    badge: "Nepal",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
  },
  {
    slug: "gold-silver-calculator",
    name: "Gold & Silver (Tola) Calculator",
    desc: "Calculate gold and silver prices in Tola, Gram, and Lal with live Nepal market rates",
    category: "Finance",
    categorySlug: "finance",
    icon: "Gem",
    badge: "Live",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: false,
  },
  {
    slug: "sip-calculator",
    name: "SIP / Mutual Fund Calculator",
    desc: "Calculate systematic investment returns, compound growth and wealth accumulation",
    category: "Finance",
    categorySlug: "finance",
    icon: "TrendingUp",
    badge: "Popular",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
  },
  {
    slug: "fd-calculator",
    name: "Fixed Deposit (FD) Calculator",
    desc: "Calculate returns on bank Fixed Deposits with compounding and 5% TDS tax",
    category: "Finance",
    categorySlug: "finance",
    icon: "Vault",
    badge: "Nepal",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
  },
  {
    slug: "vat-calculator",
    name: "13% VAT Calculator",
    desc: "Add or remove 13% Nepal Value Added Tax (VAT) from prices instantly",
    category: "Finance",
    categorySlug: "finance",
    icon: "Receipt",
    badge: "Popular",
    color: "#22C55E",
    darkColor: "#22C55E",
    isClientSide: true,
  },

  // ── Nepal ──
  {
    slug: "land-converter",
    name: "Land Unit Converter",
    desc: "Convert Ropani, Anna, Bigha, Kattha and more",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Ruler",
    badge: "Nepal",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "nepali-translator",
    name: "English ↔ Nepali Translator",
    desc: "Translate text instantly between English and Nepali Devanagari",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Languages",
    badge: "Popular",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: false,
    seoTitle: "English to Nepali Translator (Free) – Translate Instantly | SajiloTools",
    seoDescription: "Translate text between English and Nepali Devanagari instantly, free, and private — no sign-up, works right in your browser.",
  },
  {
    slug: "nepali-date-converter",
    name: "Nepali Date Converter & Age Calculator (BS ↔ AD)",
    desc: "Convert Bikram Sambat (वि.सं.) to Gregorian AD dates & calculate exact age in BS & AD with birthday countdown",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Calendar",
    badge: "Popular",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "nepali-unicode",
    name: "Nepali Unicode Typing Tool",
    desc: "Type in Romanized English and convert instantly into Devanagari Unicode",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Keyboard",
    badge: "Nepal",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },
  {
    slug: "nepali-number-words",
    name: "Nepali Number to Words",
    desc: "Convert numbers into Nepali Lakh/Crore words for bank cheques and legal documents",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "FileText",
    badge: "Popular",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },
  {
    slug: "nepali-calendar",
    name: "Nepali Calendar (BS)",
    desc: "Bikram Sambat monthly calendar grid with festivals, national holidays, and Saturdays",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "CalendarDays",
    badge: "New",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },
  {
    slug: "traditional-unit-converter",
    name: "Traditional Unit Converter (Weight & Grain)",
    desc: "Convert Dharni, Tola, Pau, Seer, Muri, Pathi, Mana and Liters/Kg",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Scale",
    badge: "Nepal",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },
  {
    slug: "vehicle-tax-calculator",
    name: "Vehicle Blue Book Tax Calculator",
    desc: "Estimate annual road tax for motorcycles, cars, EVs, and commercial vehicles across all 7 provinces",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Car",
    badge: "New",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },
  {
    slug: "ward-municipality-lookup",
    name: "Ward & Municipality Lookup",
    desc: "Find administrative details, ward counts, and official address formats across all 753 local government units in Nepal",
    category: "Nepal Tools",
    categorySlug: "nepal",
    icon: "Building2",
    badge: "Nepal",
    color: "#DC2626",
    darkColor: "#F87171",
    isClientSide: true,
  },

  // ── Everyday ──
  {
    slug: "unit-converter",
    name: "Universal Unit Converter",
    desc: "Convert length, weight, temperature, volume, area, speed, time, and data storage units",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "ArrowLeftRight",
    badge: "New",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
    featured: true,
    isLatest: true,
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    desc: "Calculate percentage of a number, percentage change, and percentage difference",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "Percent",
    badge: "Popular",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
    trending: true,
  },
  {
    slug: "gpa-percentage-converter",
    name: "GPA to Percentage Converter",
    desc: "Convert GPA to percentage and percentage to GPA using Nepal NEB and university standards",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "GraduationCap",
    badge: "Nepal",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
    isLatest: true,
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    desc: "Calculate Body Mass Index (BMI) using metric or imperial units with standard WHO categories",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "Activity",
    badge: "Free",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
  },
  {
    slug: "discount-calculator",
    name: "Discount & Markup Calculator",
    desc: "Calculate sale price after discount, original price before discount, or profit markup percentage",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "Tag",
    badge: "Popular",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
  },
  {
    slug: "bmr-calculator",
    name: "BMR & TDEE Calculator",
    desc: "Calculate Basal Metabolic Rate and Total Daily Energy Expenditure with Mifflin-St Jeor & Katch-McArdle formulas",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "Flame",
    badge: "New",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
    featured: true,
  },
  {
    slug: "calorie-calculator",
    name: "Calorie & Macro Calculator",
    desc: "Calculate daily calorie targets for weight loss, maintenance, or muscle gain with macro ratios (Protein, Carbs, Fats)",
    category: "Everyday",
    categorySlug: "everyday",
    icon: "HeartPulse",
    badge: "New",
    color: "#0D9488",
    darkColor: "#2DD4BF",
    isClientSide: true,
    trending: true,
  },
];

export function getToolsByCategory(categorySlug: string): ToolDef[] {
  return TOOLS.filter((t) => t.categorySlug === categorySlug);
}

export function getToolBySlug(slug: string): ToolDef | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export function getCategoryBySlug(slug: string): CategoryDef | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}
