import { PresetTemplate } from "./types";
import { SITE_URL } from "@/lib/site-config";

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: "nepali-business-card",
    name: "Nepali Business Card",
    description: "vCard layout with professional Sajilo dark navy and gold tones",
    type: "vcard",
    style: {
      darkColor: "#1F2544",
      lightColor: "#FFFFFF",
      colorType: "single",
      dotStyle: "classy",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      errorCorrectionLevel: "H",
    },
    defaultData: {
      firstName: "Nabin",
      lastName: "Thapa",
      phone: "+977 9800000000",
      email: "nabin@example.com",
      organization: "SajiloTools",
      jobTitle: "Developer",
      website: SITE_URL,
      city: "Kathmandu",
      country: "Nepal",
    },
  },
  {
    id: "restaurant-menu",
    name: "Restaurant Menu",
    description: "URL format with warm culinary gradient and friendly rounded dots",
    type: "url",
    style: {
      darkColor: "#D97706",
      lightColor: "#FFFBEB",
      colorType: "gradient",
      gradientType: "linear",
      gradientColor1: "#DC2626",
      gradientColor2: "#D97706",
      gradientRotation: 45,
      dotStyle: "rounded",
      cornerSquareStyle: "extra-rounded",
      cornerDotStyle: "dot",
      errorCorrectionLevel: "M",
    },
    defaultData: {
      url: `${SITE_URL}/menu`,
    },
  },
  {
    id: "guest-wifi",
    name: "Guest WiFi Network",
    description: "WiFi login configuration with sleek modern blue theme",
    type: "wifi",
    style: {
      darkColor: "#2563EB",
      lightColor: "#EFF6FF",
      colorType: "single",
      dotStyle: "dots",
      cornerSquareStyle: "dot",
      cornerDotStyle: "dot",
      errorCorrectionLevel: "M",
    },
    defaultData: {
      ssid: "ChipsyMixsy_Guest",
      password: "WelcomeToSajilo",
      encryption: "WPA",
      hidden: false,
    },
  },
  {
    id: "print-vector",
    name: "High-Contrast Print",
    description: "Maximum scannability black & white layout with high error correction",
    type: "url",
    style: {
      darkColor: "#000000",
      lightColor: "#FFFFFF",
      colorType: "single",
      dotStyle: "square",
      cornerSquareStyle: "square",
      cornerDotStyle: "square",
      errorCorrectionLevel: "H",
    },
    defaultData: {
      url: SITE_URL,
    },
  },
];
