import {
  FileText,
  Image as ImageIcon,
  AlignLeft,
  QrCode,
  Calculator,
  Palette,
  Braces,
  Link2,
  Calendar,
  Keyboard,
  RefreshCw,
  Search,
  ShieldCheck,
  Ruler,
  Hash,
  Code2,
  Wand2,
  Languages,
  MapPin,
  CalendarDays,
  ArrowLeftRight,
  ArrowDownToLine,
  Zap,
  BadgeCheck,
  Settings2,
  History,
  Heart,
  Star,
  Moon,
  Sun,
  X,
  Menu,
  ChevronDown,
  ArrowRight,
  Check,
  CheckCircle2,
  Command,
  TrendingUp,
  Boxes,
  Wrench,
  Globe2,
  ListChecks,
  ListOrdered,
  Info,
  Percent,
  Cake,
  GraduationCap,
  Activity,
  Tag,
  Building2,
  Car,
  Clock,
  Clock4,
  Crop,
  FileArchive,
  FileCheck,
  FileImage,
  Fingerprint,
  Flame,
  FlipHorizontal,
  Gem,
  HeartPulse,
  KeySquare,
  Landmark,
  LayoutGrid,
  Maximize2,
  Minimize2,
  Receipt,
  Scale,
  Squircle,
  Stamp,
  Vault,
  BookOpen,
  type LucideIcon,
} from "lucide-react";

import DeveloperSuiteIcon from "@/components/shared/DeveloperSuiteIcon";

export const ICON_MAP: Record<string, any> = {
  FileText,
  Image: ImageIcon,
  AlignLeft,
  QrCode,
  Calculator,
  Palette,
  Braces: DeveloperSuiteIcon,
  Developer: DeveloperSuiteIcon,
  Link2,
  Calendar,
  Keyboard,
  RefreshCw,
  Search,
  ShieldCheck,
  Ruler,
  Hash,
  Code2,
  Wand2,
  Languages,
  MapPin,
  CalendarDays,
  ArrowLeftRight,
  ArrowDownToLine,
  Zap,
  BadgeCheck,
  Settings2,
  History,
  Heart,
  Star,
  Moon,
  Sun,
  X,
  Menu,
  ChevronDown,
  ArrowRight,
  Check,
  CheckCircle2,
  Command,
  TrendingUp,
  Boxes,
  Wrench,
  Globe2,
  ListChecks,
  ListOrdered,
  Info,
  Percent,
  Cake,
  GraduationCap,
  Activity,
  Tag,
  Building2,
  Car,
  Clock,
  Clock4,
  Crop,
  FileArchive,
  FileCheck,
  FileImage,
  Fingerprint,
  Flame,
  FlipHorizontal,
  Gem,
  HeartPulse,
  KeySquare,
  Landmark,
  LayoutGrid,
  Maximize2,
  Minimize2,
  Receipt,
  Scale,
  Squircle,
  Stamp,
  Vault,
  BookOpen,
};

export function getToolIcon(name?: string): React.ElementType {
  if (!name) return DeveloperSuiteIcon;
  if (name === "Braces" || name === "Developer") return DeveloperSuiteIcon;
  return ICON_MAP[name] ?? DeveloperSuiteIcon;
}

export const BADGE_CONFIG: Record<
  string,
  { bg: string; text: string; darkBg: string; darkText: string }
> = {
  Popular: {
    bg: "#FEF3C7",
    text: "#B45309",
    darkBg: "#451A03",
    darkText: "#FCD34D",
  },
  Fast: {
    bg: "#DBEAFE",
    text: "#1D4ED8",
    darkBg: "#1E3A5F",
    darkText: "#93C5FD",
  },
  Free: {
    bg: "#DCFCE7",
    text: "#15803D",
    darkBg: "#052E16",
    darkText: "#86EFAC",
  },
  New: {
    bg: "#F3E8FF",
    text: "#7C3AED",
    darkBg: "#2E1065",
    darkText: "#C4B5FD",
  },
  Nepal: {
    bg: "#FEE2E2",
    text: "#DC2626",
    darkBg: "#450A0A",
    darkText: "#FCA5A5",
  },
  Updated: {
    bg: "#E0F2FE",
    text: "#0369A1",
    darkBg: "#0C2D48",
    darkText: "#7DD3FC",
  },
};
